'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18052
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\CraneChartCalc\Input\Crane List.xml")>  _
        Public Property CraneListFileSetting() As String
            Get
                Return CType(Me("CraneListFileSetting"),String)
            End Get
            Set
                Me("CraneListFileSetting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\CraneChartCalc\Input\Barge List.xml")>  _
        Public Property BargeListFileSetting() As String
            Get
                Return CType(Me("BargeListFileSetting"),String)
            End Get
            Set
                Me("BargeListFileSetting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\CraneChartCalc\Input\AllAroundRotationArray.xml")>  _
        Public Property AllAroundRotationArraySetting() As String
            Get
                Return CType(Me("AllAroundRotationArraySetting"),String)
            End Get
            Set
                Me("AllAroundRotationArraySetting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\CraneChartCalc\Input\EventLog.xml")>  _
        Public Property EventLogSetting() As String
            Get
                Return CType(Me("EventLogSetting"),String)
            End Get
            Set
                Me("EventLogSetting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\CraneChartCalc\Input\StandardCranePositions.xml")>  _
        Public Property StandardCranePositionsSetting() As String
            Get
                Return CType(Me("StandardCranePositionsSetting"),String)
            End Get
            Set
                Me("StandardCranePositionsSetting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\CraneChartCalc\Input\Criteria\")>  _
        Public Property CriteriaFolderSetting() As String
            Get
                Return CType(Me("CriteriaFolderSetting"),String)
            End Get
            Set
                Me("CriteriaFolderSetting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\CraneChartCalc\Input\OverEndRotationArray.xml")>  _
        Public Property OverEndRotationArraySetting() As String
            Get
                Return CType(Me("OverEndRotationArraySetting"),String)
            End Get
            Set
                Me("OverEndRotationArraySetting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\CraneChartCalc\Input\SimpsonMultipliers.xml")>  _
        Public Property SimpsonMultipliersSetting() As String
            Get
                Return CType(Me("SimpsonMultipliersSetting"),String)
            End Get
            Set
                Me("SimpsonMultipliersSetting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\CraneChartCalc\Input\Setup.xml")>  _
        Public Property SetupSetting() As String
            Get
                Return CType(Me("SetupSetting"),String)
            End Get
            Set
                Me("SetupSetting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\CraneChartCalc\Input\Sheet.xltx")>  _
        Public Property XLSXTemplateSetting() As String
            Get
                Return CType(Me("XLSXTemplateSetting"),String)
            End Get
            Set
                Me("XLSXTemplateSetting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\CraneChartCalc\Input\Hydrostatics\")>  _
        Public Property HydrostaticsFolderSetting() As String
            Get
                Return CType(Me("HydrostaticsFolderSetting"),String)
            End Get
            Set
                Me("HydrostaticsFolderSetting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\CraneChartCalc\Input\CrossCurves\")>  _
        Public Property CrossCurveFolderSetting() As String
            Get
                Return CType(Me("CrossCurveFolderSetting"),String)
            End Get
            Set
                Me("CrossCurveFolderSetting") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CraneChartCalc.My.MySettings
            Get
                Return Global.CraneChartCalc.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
